package com.java.concepts.modernjava.java17.records;

//java 17 feature

import java.util.Objects;

public record Product(
        int id,
        String name,
        double price) {

    public Product {

        if(name!=null && name.isBlank()){
            throw new IllegalArgumentException("Product name cannot be blank");
        }
        if (price < 0 ){
            throw new IllegalArgumentException("Product price cannot be negative");
        }
    }

    //custom compact constructor
    public Product(int id, String name){

        this(id, name, 200.0);
    }

    public String upperCaseName(){
        return name.toUpperCase();
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, name, price);
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (!(obj instanceof Product product)) {
            return false;
        }
        return Objects.equals(id, product.id) &&
                Objects.equals(price, product.price);
    }
}

// By default, the constructors that are generated by the compiler are called canonical constructors.
// They take parameters that match the record components and assign them to the corresponding fields.
// However, you can also define your own custom constructors
// if you need to perform additional validation or initialization logic.